//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSolutions
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int TaskId { get; set; }
        public string PlayerTaskSolution { get; set; }
        public Nullable<bool> IsSolutionCorrect { get; set; }
    }
}
